// deno-lint-ignore-file
// .densky/http/feats.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";
import $child$0 from "./feats/cookies.ts";
import $child$1 from "./feats/cookies/_index.ts";

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.pathname;
  if (urlMatcherPrepare_pathname.startsWith("/feats")) {
    const out$0 = await $child$0(req);
    if (out$0) return out$0;
    const out$1 = await $child$1(req);
    if (out$1) return out$1;
  }
}

export default handler;
