// THIS FILE WAS GENERATED BY DENSKY-BACKEND (By Apika Luca)
import * as $Densky$ from "densky";
import httpHandler from "./http.main.ts";
import staticHandler from "./static.main.ts";
import wsHandler from "./ws.main.ts";

$Densky$.HTTPResponse.viewsTree = new $Densky$.StaticFiles(
  "src/views",
  "views",
);

export default async function requestHandler(
  request: Deno.RequestEvent,
  conn: Deno.Conn,
): Promise<Response> {
  const req = new $Densky$.HTTPRequest(request);

  const staticRes = await staticHandler(req);
  if (staticRes) return staticRes;

  const wsRes = await wsHandler(req);
  if (wsRes) return wsRes;

  return await httpHandler(req);
}
